id: P000384
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:37:11.444249
source_metadata:
  id: bdr:W28969
  title: རྒྱ་བོད་ཚན་རྩལ་ལོ་ཙཱའི་གཞུང་ལུགས་ཀྱི་རྣམ་བཤད།
  author: ''
  volumes:
    4ca703c14c1447478e93f4b6b79ab377:
      image_group_id: I1KG22677
      title: Volume 1 of rgya bod tshan rtsal lo tsA'i gzhung lugs kyi rnam bshad
      volume_number: 1
      total_pages: 316
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
